openapi: 3.2.0
info:
  title: A7 Analytics Platform - (RDI) version 2 Reference data API
  description: A7 Analytics Platform for the main T7 trading venues of Deutsche Börse Group.
  contact:
    name: Deutsche Börse Data & Analytics
    url: https://www.mds.deutsche-boerse.com
    email: analytics@deutsche-boerse.com
  version: 2.0.0
servers:
- url: /api/v2
  description: A7 production environment
security:
- bearerAuth: []
tags:
- name: Reference Data API
paths:
  /rdi/:
    get:
      tags:
      - Reference Data API
      summary: Retrieve list of markets
      description: The request delivers all available markets as a list of marketIds.
      operationId: getMarkets
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Markets'
            application/gzip:
              schema:
                $ref: '#/components/schemas/Markets'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/:
    get:
      tags:
      - Reference Data API
      summary: Retrieve list of trading days
      description: The request delivers all available trading days for the selected market as a list of dates.
      operationId: getDates
      parameters:
      - $ref: '#/components/parameters/marketId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dates'
            application/gzip:
              schema:
                $ref: '#/components/schemas/Dates'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/:
    get:
      tags:
      - Reference Data API
      summary: Retrieve list of market segments
      description: The request delivers all available market segments for the selected market and trading day as a list of marketSegmentIds.
      operationId: getMarketSegments
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketSegments'
            application/gzip:
              schema:
                $ref: '#/components/schemas/MarketSegments'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}:
    get:
      tags:
      - Reference Data API
      summary: Retrieve details for all market segments
      description: The request delivers details for all available market segments for the selected market and trading day as a list of objects. The details contain all available ProductSnapshot (BU) messages.
      operationId: getMarketSegmentOverview
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/annotation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketSegmentsOverview'
            application/gzip:
              schema:
                $ref: '#/components/schemas/MarketSegmentsOverview'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/{marketSegmentId}/:
    get:
      tags:
      - Reference Data API
      summary: Retrieve list of securities
      description: The request delivers all available securities for the selected market, trading day and market segment as a list securityIds.
      operationId: getSecurities
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/marketSegmentId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Securities'
            application/gzip:
              schema:
                $ref: '#/components/schemas/Securities'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/{marketSegmentId}:
    get:
      tags:
      - Reference Data API
      summary: Retrieve market segment details
      description: The request delivers all available details for the selected market segment as a list of objects. The details contain all RDI messages connected to the market segment. The message types ProductSnapshot (BU), InstrumentSnapshot (d), TotalReturnFutureStatus (f), TradeAtReferencePriceStatus (f) and VarianceFuturesStatus (f) can be expected.
      operationId: getMarketSegmentDetails
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/marketSegmentId'
      - $ref: '#/components/parameters/annotation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketSegmentDetails'
            application/gzip:
              schema:
                $ref: '#/components/schemas/MarketSegmentDetails'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/{marketSegmentId}/{securityId}/:
    get:
      tags:
      - Reference Data API
      summary: Retrieve list of messages
      description: The request delivers all available messages for the selected market, trading day, market segment and security as a list of msgSeqNums.
      operationId: getMessages
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/marketSegmentId'
      - $ref: '#/components/parameters/securityId'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Messages'
            application/gzip:
              schema:
                $ref: '#/components/schemas/Messages'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/{marketSegmentId}/{securityId}:
    get:
      tags:
      - Reference Data API
      summary: Retrieve security details
      description: The request delivers all available details for the selected market segment and security as a list of objects. The details contain all RDI messages connected to the market segment and security. The message types InstrumentSnapshot (d), TotalReturnFutureStatus (f), TradeAtReferencePriceStatus (f) and VarianceFuturesStatus (f) can be expected.
      operationId: getSecurityDetails
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/marketSegmentId'
      - $ref: '#/components/parameters/securityId'
      - $ref: '#/components/parameters/annotation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SecurityDetails'
            application/gzip:
              schema:
                $ref: '#/components/schemas/SecurityDetails'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
  /rdi/{marketId}/{date}/{marketSegmentId}/{securityId}/{msgSeqNum}:
    get:
      tags:
      - Reference Data API
      summary: Retrieve message details
      description: The request delivers the message details for the selected market, trading day, market segment, security and message as an array of objects. Depending on the type of message, the content of the objects may differ. The message types InstrumentSnapshot (d), TotalReturnFutureStatus (f), TradeAtReferencePriceStatus (f) and VarianceFuturesStatus (f) can be expected.
      operationId: getMessageDetails
      parameters:
      - $ref: '#/components/parameters/marketId'
      - $ref: '#/components/parameters/date'
      - $ref: '#/components/parameters/marketSegmentId'
      - $ref: '#/components/parameters/securityId'
      - $ref: '#/components/parameters/msgSeqNum'
      - $ref: '#/components/parameters/annotation'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDetails'
            application/gzip:
              schema:
                $ref: '#/components/schemas/MessageDetails'
                format: binary
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '404':
          $ref: '#/components/responses/404'
components:
  parameters:
    date:
      name: date
      in: path
      description: Trading day in the format  YYYYMMDD
      example: 20200106
      required: true
      schema:
        type: integer
        format: uint32
        pattern: ^\d{8}$
    securityId:
      name: securityId
      in: path
      description: Unique security identifier on T7
      example: '5036012'
      required: true
      schema:
        type: integer
        format: int64
    msgSeqNum:
      name: msgSeqNum
      in: path
      description: Message sequence number
      example: '4720'
      required: true
      schema:
        type: integer
        format: uint32
    marketSegmentId:
      name: marketSegmentId
      in: path
      description: Unique product identifier or product pool identifier on T7
      example: '204934'
      required: true
      schema:
        type: integer
        format: uint32
    marketId:
      name: marketId
      in: path
      description: Market identifier code as specified in ISO 10383. Available markets are XEEE, XETR and XEUR.
      example: XEUR
      required: true
      schema:
        type: string
    annotation:
      name: annotation
      in: query
      description: "Define the output format of enumerations.<br/> annotation options:\n  * `unannotated` (default) - enums are represented by their raw values\n  * `humanreadable` - enums are represented by their human readable strings\n  * `annotated` - enums are represented by both their human readable strings and raw values\n"
      required: false
      schema:
        type: string
        enum:
        - unannotated
        - humanreadable
        - annotated
        default: unannotated
  schemas:
    ProductSnapshot:
      type: object
      description: ProductSnapshot (BU) message details. Please see the T7 RDI documentation for details about the available fields for the different message types.
      example:
        Template: ProductSnapshot
        MsgType: BU
        MsgSeqNum: 1913
        MarketID: XEUR
        MarketSegmentID: 204934
        EffectiveBusinessDate: 20210315
        NextEffectiveBusinessDate: 20210316
        MarketSegment: TC1L
        MarketSegmentStatus: '1'
        PartitionID: 6
        DerivativesDescriptorGroup:
          Currency: EUR
          MarketSegmentDesc: TRF ON EURGP1LCOLL
          MarketSegmentSymbol: DE000A26RR59
          ParentMktSegmID: FINX
          USApproval: None
          OffsetSTPEffectiveTime: 10
        UnderlyingDescriptorGroup:
          UnderlyingSecurityExchange: XSTX
          UnderlyingSymbol: 1CLE
          UnderlyingSecurityID: CH0478459768
          UnderlyingSecurityIDSource: '4'
          UnderlyingPrevClosePx: 233.66
        NoInstrumentScopes: 1
        InstrumentScopes:
        - InstrumentScopeOperator: '1'
          InstrumentScopeSecurityType: TRF
        BaseTrdgRules:
          NoTickRules: 1
          TickRules:
          - TickRuleID: 13
            StartTickPriceRange: 0
            EndTickPriceRange: 9999999999.9999
            TickIncrement: 0.5
            NoTickRuleScopes: 1
            TickRuleScopes:
            - TickRuleProductComplex: '1'
              TrdType: '0'
          NoPriceRangeRules: 1
          PriceRangeRules:
          - PriceRangeRuleID: 489
            PriceRangeProductComplex: '1'
            StartPriceRange: 0
            EndPriceRange: 9999999999.9999
            PriceRangeValue: 20
          QuoteSideIndicator: '1'
          QuoteSideModelType: '0'
          FastMarketPercentage: 100
        BaseTrdgRulesDerivatives:
          NoQuoteSizeRules: 2
          QuoteSizeRules:
          - MinBidSize: 1
            MinOfferSize: 1
            FastMarketIndicator: '0'
          - MinBidSize: 1
            MinOfferSize: 1
            FastMarketIndicator: '1'
          NoFlexProductEligibilities: 0
          FlexRules: []
          RoundLot: 1
        NoMatchRules: 1
        MatchRules:
        - MatchRuleProductComplex: '1'
          MatchAlgorithm: PT
        NoMDFeedTypes: 5
        Feeds:
        - MDFeedType: HS
          MDBookType: '3'
          PrimaryServiceLocationID: 224.0.114.42
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.114.74
          SecondaryServiceLocationSubID: 59032
        - MDFeedType: HI
          MDBookType: '3'
          MarketDepthTimeInterval: 0
          PrimaryServiceLocationID: 224.0.114.43
          PrimaryServiceLocationSubID: 59033
          SecondaryServiceLocationID: 224.0.114.75
          SecondaryServiceLocationSubID: 59033
        - MDFeedType: HS
          MDBookType: '2'
          MarketDepth: 10
          MDRecoveryTimeInterval: 120000
          PrimaryServiceLocationID: 224.0.50.14
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.50.142
          SecondaryServiceLocationSubID: 59032
        - MDFeedType: HI
          MDBookType: '2'
          MarketDepth: 10
          MarketDepthTimeInterval: 0
          PrimaryServiceLocationID: 224.0.50.15
          PrimaryServiceLocationSubID: 59033
          SecondaryServiceLocationID: 224.0.50.143
          SecondaryServiceLocationSubID: 59033
        - MDFeedType: L
          MDBookType: '2'
          MarketDepth: 5
          MarketDepthTimeInterval: 2000
          MDRecoveryTimeInterval: 300000
          PrimaryServiceLocationID: 224.0.50.73
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.50.201
          SecondaryServiceLocationSubID: 59032
    MarketSegments:
      type: array
      items:
        type: integer
        format: uint32
      example:
      - 3
      - 4
      - 8
      - 9
      - 10
    Securities:
      type: array
      items:
        type: string
        format: int64
      example:
      - '4799382'
      - '5036064'
      - '5141210'
      - '5222340'
      - '5336489'
      - '5428018'
      - '5519919'
      - '5594891'
      - '5694799'
      - '3595763'
      - '5914234'
      - '6014211'
      - '6119243'
      - '4557556'
      - '5824719'
      - '72057611217797215'
    MarketSegmentsOverview:
      type: array
      description: An array of objects containing all available ProductSnapshots (BU) message details.
      items:
        $ref: '#/components/schemas/ProductSnapshot'
    MessageDetails:
      type: array
      description: An array of objects.
      items:
        type: object
        description: Message object of type InstrumentSnapshot (d) or SecurityStatus (f). Please refer to the T7 RDI documentation for details about the available fields for the different message types.
      example:
      - Template: InstrumentSnapshot
        MsgType: d
        MsgSeqNum: 1914
        SecurityID: '5036012'
        SecurityIDSource: M
        NoSecurityAltID: 2
        SecurityAlt:
        - SecurityAltID: '365625353'
          SecurityAltIDSource: M
        - SecurityAltID: DE000C47BX29
          SecurityAltIDSource: '4'
        SecurityType: TRF
        SecurityStatus: '1'
        SecurityDesc: TC1L SI 20210319 CS
        ProductComplex: '1'
        DerivativesDescriptorGroup:
          CFICode: FFICSX
          SimpleInstrumentDescriptorGroup:
            ContractDate: 20210319
            ContractMonthYear: 202103
            ContractMultiplier: 1
            ValuationMethod: FUT
            SettlMethod: C
            PriorSettlPrice: 234.909
        NoInstrAttrib: 5
        InstrumentAttributes:
        - InstrAttribType: '123'
          InstrAttribValue: N
        - InstrAttribType: '106'
          InstrAttribValue: XEUR
        - InstrAttribType: '112'
          InstrAttribValue: Y
        - InstrAttribType: '113'
          InstrAttribValue: N
        - InstrAttribType: '115'
          InstrAttribValue: N
        NoEvents: 1
        Events:
        - EventType: '7'
          EventDate: 20210318
        InstrumentPricePrecision: 4
        MinPriceIncrement: 0.5
        MinPriceIncrementClearing: 0.0002
        MinPriceIncrementAmount: 0.01
        MaturityDate: 20210319
        MaturityMonthYear: 202103
        NoMarketSegments: 1
        MarketSegmentGrp:
        - MarketSegmentID: 204934
          PriceType: '22'
          NoPriceRangeRules: 1
          PriceRangeRules:
          - PriceRangeRuleID: 489
    MarketSegmentDetails:
      type: array
      description: An array of objects containing all messages connected to the security.
      items:
        type: object
        description: Message object of type ProductSnapshot (BU), InstrumentSnapshot (d) or SecurityStatus (f). Please refer to the T7 RDI documentation for details about the available fields for the different message types.
      example:
      - Template: ProductSnapshot
        MsgType: BU
        MsgSeqNum: 1913
        MarketID: XEUR
        MarketSegmentID: 204934
        EffectiveBusinessDate: 20210315
        NextEffectiveBusinessDate: 20210316
        MarketSegment: TC1L
        MarketSegmentStatus: '1'
        PartitionID: 6
        DerivativesDescriptorGroup:
          Currency: EUR
          MarketSegmentDesc: TRF ON EURGP1LCOLL
          MarketSegmentSymbol: DE000A26RR59
          ParentMktSegmID: FINX
          USApproval: None
          OffsetSTPEffectiveTime: 10
        UnderlyingDescriptorGroup:
          UnderlyingSecurityExchange: XSTX
          UnderlyingSymbol: 1CLE
          UnderlyingSecurityID: CH0478459768
          UnderlyingSecurityIDSource: '4'
          UnderlyingPrevClosePx: 233.66
        NoInstrumentScopes: 1
        InstrumentScopes:
        - InstrumentScopeOperator: '1'
          InstrumentScopeSecurityType: TRF
        BaseTrdgRules:
          NoTickRules: 1
          TickRules:
          - TickRuleID: 13
            StartTickPriceRange: 0
            EndTickPriceRange: 9999999999.9999
            TickIncrement: 0.5
            NoTickRuleScopes: 1
            TickRuleScopes:
            - TickRuleProductComplex: '1'
              TrdType: '0'
          NoPriceRangeRules: 1
          PriceRangeRules:
          - PriceRangeRuleID: 489
            PriceRangeProductComplex: '1'
            StartPriceRange: 0
            EndPriceRange: 9999999999.9999
            PriceRangeValue: 20
          QuoteSideIndicator: '1'
          QuoteSideModelType: '0'
          FastMarketPercentage: 100
        BaseTrdgRulesDerivatives:
          NoQuoteSizeRules: 2
          QuoteSizeRules:
          - MinBidSize: 1
            MinOfferSize: 1
            FastMarketIndicator: '0'
          - MinBidSize: 1
            MinOfferSize: 1
            FastMarketIndicator: '1'
          NoFlexProductEligibilities: 0
          FlexRules: []
          RoundLot: 1
        NoMatchRules: 1
        MatchRules:
        - MatchRuleProductComplex: '1'
          MatchAlgorithm: PT
        NoMDFeedTypes: 5
        Feeds:
        - MDFeedType: HS
          MDBookType: '3'
          PrimaryServiceLocationID: 224.0.114.42
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.114.74
          SecondaryServiceLocationSubID: 59032
        - MDFeedType: HI
          MDBookType: '3'
          MarketDepthTimeInterval: 0
          PrimaryServiceLocationID: 224.0.114.43
          PrimaryServiceLocationSubID: 59033
          SecondaryServiceLocationID: 224.0.114.75
          SecondaryServiceLocationSubID: 59033
        - MDFeedType: HS
          MDBookType: '2'
          MarketDepth: 10
          MDRecoveryTimeInterval: 120000
          PrimaryServiceLocationID: 224.0.50.14
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.50.142
          SecondaryServiceLocationSubID: 59032
        - MDFeedType: HI
          MDBookType: '2'
          MarketDepth: 10
          MarketDepthTimeInterval: 0
          PrimaryServiceLocationID: 224.0.50.15
          PrimaryServiceLocationSubID: 59033
          SecondaryServiceLocationID: 224.0.50.143
          SecondaryServiceLocationSubID: 59033
        - MDFeedType: L
          MDBookType: '2'
          MarketDepth: 5
          MarketDepthTimeInterval: 2000
          MDRecoveryTimeInterval: 300000
          PrimaryServiceLocationID: 224.0.50.73
          PrimaryServiceLocationSubID: 59032
          SecondaryServiceLocationID: 224.0.50.201
          SecondaryServiceLocationSubID: 59032
      - Template: InstrumentSnapshot
        MsgType: d
        MsgSeqNum: 1914
        SecurityID: '5036012'
        SecurityIDSource: M
        NoSecurityAltID: 2
        SecurityAlt:
        - SecurityAltID: '365625353'
          SecurityAltIDSource: M
        - SecurityAltID: DE000C47BX29
          SecurityAltIDSource: '4'
        SecurityType: TRF
        SecurityStatus: '1'
        SecurityDesc: TC1L SI 20210319 CS
        ProductComplex: '1'
        DerivativesDescriptorGroup:
          CFICode: FFICSX
          SimpleInstrumentDescriptorGroup:
            ContractDate: 20210319
            ContractMonthYear: 202103
            ContractMultiplier: 1
            ValuationMethod: FUT
            SettlMethod: C
            PriorSettlPrice: 234.909
        NoInstrAttrib: 5
        InstrumentAttributes:
        - InstrAttribType: '123'
          InstrAttribValue: N
        - InstrAttribType: '106'
          InstrAttribValue: XEUR
        - InstrAttribType: '112'
          InstrAttribValue: Y
        - InstrAttribType: '113'
          InstrAttribValue: N
        - InstrAttribType: '115'
          InstrAttribValue: N
        NoEvents: 1
        Events:
        - EventType: '7'
          EventDate: 20210318
        InstrumentPricePrecision: 4
        MinPriceIncrement: 0.5
        MinPriceIncrementClearing: 0.0002
        MinPriceIncrementAmount: 0.01
        MaturityDate: 20210319
        MaturityMonthYear: 202103
        NoMarketSegments: 1
        MarketSegmentGrp:
        - MarketSegmentID: 204934
          PriceType: '22'
          NoPriceRangeRules: 1
          PriceRangeRules:
          - PriceRangeRuleID: 489
      - Template: TotalReturnFuturesStatus
        MsgType: f
        MsgSeqNum: 1915
        MarketSegmentID: 204934
        SecurityID: '5036012'
        SecurityIDSource: M
        SecurityType: TRF
        PriorSettlPrice: 159
        NoClearingPriceParameters: 2
        ClearingPriceParameters:
        - BusinessDayType: '5'
        - BusinessDayType: '1'
          AnnualCalendarDays: 360
          RemainingCalendarDays: 6
    Markets:
      type: array
      items:
        type: string
      example:
      - XEEE
      - XETR
      - XEUR
    Dates:
      type: array
      items:
        type: integer
        format: uint32
      example:
      - 20200102
      - 20200103
      - 20200106
    SecurityDetails:
      type: array
      description: An array of objects containing all messages connected to the security.
      items:
        type: object
        description: Message object of type InstrumentSnapshot (d) or SecurityStatus (f). Please refer to the T7 RDI documentation for details about the available fields for the different message types.
      example:
      - Template: InstrumentSnapshot
        MsgType: d
        MsgSeqNum: 1914
        SecurityID: '5036012'
        SecurityIDSource: M
        NoSecurityAltID: 2
        SecurityAlt:
        - SecurityAltID: '365625353'
          SecurityAltIDSource: M
        - SecurityAltID: DE000C47BX29
          SecurityAltIDSource: '4'
        SecurityType: TRF
        SecurityStatus: '1'
        SecurityDesc: TC1L SI 20210319 CS
        ProductComplex: '1'
        DerivativesDescriptorGroup:
          CFICode: FFICSX
          SimpleInstrumentDescriptorGroup:
            ContractDate: 20210319
            ContractMonthYear: 202103
            ContractMultiplier: 1
            ValuationMethod: FUT
            SettlMethod: C
            PriorSettlPrice: 234.909
        NoInstrAttrib: 5
        InstrumentAttributes:
        - InstrAttribType: '123'
          InstrAttribValue: N
        - InstrAttribType: '106'
          InstrAttribValue: XEUR
        - InstrAttribType: '112'
          InstrAttribValue: Y
        - InstrAttribType: '113'
          InstrAttribValue: N
        - InstrAttribType: '115'
          InstrAttribValue: N
        NoEvents: 1
        Events:
        - EventType: '7'
          EventDate: 20210318
        InstrumentPricePrecision: 4
        MinPriceIncrement: 0.5
        MinPriceIncrementClearing: 0.0002
        MinPriceIncrementAmount: 0.01
        MaturityDate: 20210319
        MaturityMonthYear: 202103
        NoMarketSegments: 1
        MarketSegmentGrp:
        - MarketSegmentID: 204934
          PriceType: '22'
          NoPriceRangeRules: 1
          PriceRangeRules:
          - PriceRangeRuleID: 489
      - Template: TotalReturnFuturesStatus
        MsgType: f
        MsgSeqNum: 1915
        MarketSegmentID: 204934
        SecurityID: '5036012'
        SecurityIDSource: M
        SecurityType: TRF
        PriorSettlPrice: 159
        NoClearingPriceParameters: 2
        ClearingPriceParameters:
        - BusinessDayType: '5'
        - BusinessDayType: '1'
          AnnualCalendarDays: 360
          RemainingCalendarDays: 6
    Messages:
      type: array
      items:
        type: integer
        format: uint32
      example:
      - 7474
      - 7475
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
